name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'
  run_main:
    description: 'Your input description here'
    required: true
    default: 'true'
  run_post:
    description: 'Your input description here'
    required: true
    default: 'true'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
  post: dist/index.js
